# Generated by Django 4.2.4 on 2023-09-02 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('class_id', models.IntegerField(blank=True, null=True)),
                ('class_name', models.TextField()),
                ('create_date', models.TextField()),
                ('last_update', models.TextField()),
                ('create_user_id', models.IntegerField(blank=True, null=True)),
                ('update_user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbObj_par', to='person.dbobject')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=555)),
                ('last_name', models.CharField(max_length=555)),
                ('patronymic', models.CharField(max_length=555)),
                ('date_of_birth', models.CharField(max_length=777)),
                ('gender', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=666)),
                ('dbobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbObj_person', to='person.dbobject')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbObj', to='person.dbobject')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teach_per', to='person.person')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=555)),
                ('dbobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbObj_stu', to='person.dbobject')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='person.parents')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='par_stu', to='person.person')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.AddField(
            model_name='parents',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='par_pers', to='person.person'),
        ),
    ]
