# Generated by Django 4.2.4 on 2023-09-03 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('dbobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.dbobject')),
                ('caption', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fullInfo', models.TextField()),
                ('files', models.FileField(upload_to='file/')),
                ('images', models.FileField(upload_to='img/')),
                ('img_cat', models.FileField(upload_to='com_img_cat/')),
                ('file_cat', models.FileField(upload_to='com_file_cat/')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
            },
            bases=('person.dbobject',),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('dbobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.dbobject')),
                ('caption', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('extension', models.IntegerField(blank=True, null=True)),
                ('files', models.FileField(upload_to='files/')),
            ],
            bases=('person.dbobject',),
        ),
        migrations.CreateModel(
            name='FileCategories',
            fields=[
                ('dbobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.dbobject')),
                ('file_cat', models.FileField(upload_to='file_cat/')),
            ],
            bases=('person.dbobject',),
        ),
        migrations.CreateModel(
            name='ImageCategories',
            fields=[
                ('dbobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.dbobject')),
                ('image', models.FileField(upload_to='img_cat/')),
            ],
            bases=('person.dbobject',),
        ),
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('dbobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.dbobject')),
                ('caption', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('items', models.FileField(upload_to='items/')),
            ],
            bases=('person.dbobject',),
        ),
        migrations.CreateModel(
            name='ComponentFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='component.file')),
                ('title', models.CharField(max_length=255)),
            ],
            bases=('component.file',),
        ),
        migrations.CreateModel(
            name='ComponentFileCategories',
            fields=[
                ('filecategories_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='component.filecategories')),
                ('title', models.CharField(max_length=255)),
            ],
            bases=('component.filecategories',),
        ),
        migrations.CreateModel(
            name='ComponentIMGCategories',
            fields=[
                ('imagecategories_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='component.imagecategories')),
                ('title', models.CharField(max_length=255)),
            ],
            bases=('component.imagecategories',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='component.file')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('heigth', models.IntegerField(blank=True, null=True)),
                ('alt', models.FileField(upload_to='alt/')),
            ],
            bases=('component.file',),
        ),
        migrations.CreateModel(
            name='ComponentImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='component.image')),
                ('title', models.CharField(max_length=255)),
            ],
            bases=('component.image',),
        ),
        migrations.CreateModel(
            name='Stakeholders',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='component.component')),
                ('add', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeh_student', to='person.students')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeh_teach', to='person.teachers')),
            ],
            options={
                'verbose_name': 'Стейкхолдер',
                'verbose_name_plural': 'Стейкхолдеры',
            },
            bases=('component.component',),
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='component.component')),
                ('add', models.DateField(auto_now_add=True)),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_teach', to='person.teachers')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
            bases=('component.component',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='component.component')),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
            bases=('component.component',),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='component.component')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teach_courses', to='person.teachers')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
            bases=('component.component',),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='component.component')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('com_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_news', to='component.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
            bases=('component.component',),
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='component.component')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards_stud', to='person.students')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
            },
            bases=('component.component',),
        ),
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='component.component')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teach_advant', to='person.teachers')),
            ],
            options={
                'verbose_name': 'Преимущества',
                'verbose_name_plural': 'Преимуществы',
            },
            bases=('component.component',),
        ),
    ]
