# Generated by Django 4.2.4 on 2023-09-02 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fullInfo', models.TextField()),
                ('files', models.FileField(upload_to='file/')),
                ('images', models.FileField(upload_to='img/')),
                ('db_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_db', to='person.dbobject')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('extension', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='file/')),
                ('db_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_db_obj', to='person.dbobject')),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555)),
                ('add', models.DateField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_stakeholders', to='component.component')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeh_student', to='person.students')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeh_teach', to='person.teachers')),
            ],
            options={
                'verbose_name': 'Стейкхолдер',
                'verbose_name_plural': 'Стейкхолдеры',
            },
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=555)),
                ('add', models.DateField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_prof', to='component.component')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_teach', to='person.teachers')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_news', to='component.component')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('items', models.FileField(upload_to='items/')),
                ('db_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='med_cat_obj', to='person.dbobject')),
            ],
        ),
        migrations.CreateModel(
            name='ImageCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='img_cat/')),
                ('db_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_img_cat', to='person.dbobject')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('heigth', models.IntegerField(blank=True, null=True)),
                ('alt', models.FileField(upload_to='alt/')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_img', to='component.file')),
            ],
        ),
        migrations.CreateModel(
            name='FileCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file_cat/')),
                ('db_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_file_cat', to='person.dbobject')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_courses', to='component.component')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stud_courses', to='person.students')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teach_courses', to='person.teachers')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='ComponentIMGCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_img_cat', to='component.imagecategories')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_img', to='component.image')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentFileCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_file_cat', to='component.filecategories')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_file', to='component.file')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='file_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_file', to='component.filecategories'),
        ),
        migrations.AddField(
            model_name='component',
            name='img_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_img', to='component.imagecategories'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_com', to='component.component')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_news', to='component.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_com', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_awards', to='component.component')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards_stud', to='person.students')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
            },
        ),
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_advant', to='component.component')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teach_advant', to='person.teachers')),
            ],
            options={
                'verbose_name': 'Преимущества',
                'verbose_name_plural': 'Преимуществы',
            },
        ),
    ]
